# -*- coding: utf-8 -*-
"""Vishal_version_botnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgTYWMCqOD5tRKrCvZGrCvYlABLbIL5_
"""

# -*- coding: utf-8 -*-
"""
Botnet Detection — UNSW-NB15 Dataset
Fixed & Improved: PCA in pipeline, RandomizedSearchCV, sklearn Pipeline,
stratified CV, ROC-AUC, clean inference, autoencoder anomaly detection.
"""

# ============================================================
# 0. COLAB SETUP
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/botnet_datasets')

# ============================================================
# 1. IMPORTS & PATHS
# ============================================================
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

train_path    = "/content/drive/MyDrive/botnet_datasets/UNSW_NB15_training-set.csv"
test_path     = "/content/drive/MyDrive/botnet_datasets/UNSW_NB15_testing-set.csv"
features_path = "/content/drive/MyDrive/botnet_datasets/NUSW-NB15_features.csv"

# ============================================================
# 2. LOAD DATA
# ============================================================
train_df = pd.read_csv(train_path)
test_df  = pd.read_csv(test_path)

print("Training shape :", train_df.shape)
print("Testing  shape :", test_df.shape)
train_df.info()

# ============================================================
# 3. PREPROCESSING
# ============================================================
# Drop non-feature columns
train_df = train_df.drop(columns=['id', 'attack_cat'])
test_df  = test_df.drop(columns=['id', 'attack_cat'])

# One-Hot Encoding for categorical features
categorical_cols = ['proto', 'service', 'state']
train_df = pd.get_dummies(train_df, columns=categorical_cols)
test_df  = pd.get_dummies(test_df,  columns=categorical_cols)

# Align: keep training columns as the reference (fill missing with 0)
train_df, test_df = train_df.align(test_df, join='left', axis=1, fill_value=0)

print("After OHE — train:", train_df.shape, " test:", test_df.shape)

# ============================================================
# 4. FEATURE ENGINEERING  (encapsulated to reuse at inference)
# ============================================================
def safe_log(x):
    """Log1p with clip to prevent overflow."""
    return np.log1p(np.clip(x, 0, 1e6))


def add_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add domain-driven network traffic features."""
    df = df.copy()
    df["packet_ratio"]      = safe_log(df["spkts"] / (df["dpkts"] + 1))
    df["byte_ratio"]        = safe_log(df["sbytes"] / (df["dbytes"] + 1))
    df["traffic_intensity"] = safe_log(df["rate"] * df["dur"])
    df["avg_packet_size"]   = safe_log(
        (df["sbytes"] + df["dbytes"]) / (df["spkts"] + df["dpkts"] + 1)
    )
    df["ttl_difference"]    = safe_log(abs(df["sttl"] - df["dttl"]))
    df["packet_rate"]       = safe_log(
        (df["spkts"] + df["dpkts"]) / (df["dur"] + 0.001)
    )
    return df


train_df = add_features(train_df)
test_df  = add_features(test_df)

print("After feature engineering — train:", train_df.shape)

# ============================================================
# 5. TRAIN / TEST SPLIT
# ============================================================
X_train = train_df.drop("label", axis=1)
y_train = train_df["label"]

X_test  = test_df.drop("label", axis=1)
y_test  = test_df["label"]

# Store column list BEFORE SMOTE (inference will use these)
FEATURE_COLUMNS = X_train.columns.tolist()

print("X_train:", X_train.shape, "| X_test:", X_test.shape)
print("Class distribution (train):\n", y_train.value_counts())

# ============================================================
# 6. SMOTE  (only on training data)
# ============================================================
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("After SMOTE:", X_train_res.shape)
print("Class distribution after SMOTE:\n", pd.Series(y_train_res).value_counts())

# ============================================================
# 7. PIPELINE FACTORY  — RobustScaler → PCA → Classifier
# ============================================================
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline


# n_components=0.95 retains enough principal components to explain 95% variance.
# This is better than a fixed integer because it adapts to any feature space size.
PCA_VARIANCE = 0.95


def make_pipeline(clf) -> Pipeline:
    """Build a clean sklearn Pipeline: scale → PCA → model."""
    return Pipeline([
        ("scaler", RobustScaler()),
        ("pca",    PCA(n_components=PCA_VARIANCE, random_state=42)),
        ("clf",    clf),
    ])

# ============================================================
# 8. HYPERPARAMETER TUNING — RandomizedSearchCV
#    Rationale: RandomizedSearchCV over GridSearchCV because
#    the search spaces are large (~200-400 combos each).
#    n_iter=20 gives a good quality/speed trade-off.
# ============================================================
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, roc_auc_score, roc_curve, auc,
)

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
SCORING = "f1"
N_ITER  = 20

# ----------------------------------------------------------------
# 8a. Random Forest
# ----------------------------------------------------------------
rf_param_dist = {
    "clf__n_estimators":      [100, 200, 300],
    "clf__max_depth":         [None, 10, 20, 30],
    "clf__min_samples_split": [2, 5, 10],
    "clf__min_samples_leaf":  [1, 2, 4],
    "clf__max_features":      ["sqrt", "log2"],
}

rf_search = RandomizedSearchCV(
    estimator           = make_pipeline(RandomForestClassifier(n_jobs=-1, random_state=42)),
    param_distributions = rf_param_dist,
    n_iter              = N_ITER,
    scoring             = SCORING,
    cv                  = cv,
    random_state        = 42,
    n_jobs              = -1,
    verbose             = 1,
    refit               = True,
)
rf_search.fit(X_train_res, y_train_res)
print("\nBest RF params :", rf_search.best_params_)
print("Best RF CV F1  :", round(rf_search.best_score_, 4))
rf_model = rf_search.best_estimator_

# ----------------------------------------------------------------
# 8b. XGBoost
# ----------------------------------------------------------------
xgb_param_dist = {
    "clf__n_estimators":     [100, 200, 300],
    "clf__max_depth":        [4, 6, 8, 10],
    "clf__learning_rate":    [0.01, 0.05, 0.1, 0.2],
    "clf__subsample":        [0.6, 0.8, 1.0],
    "clf__colsample_bytree": [0.6, 0.8, 1.0],
    "clf__gamma":            [0, 0.1, 0.3],
}

xgb_search = RandomizedSearchCV(
    estimator           = make_pipeline(
                            XGBClassifier(
                                n_jobs=-1, random_state=42,
                                eval_metric='logloss',
                            )
                          ),
    param_distributions = xgb_param_dist,
    n_iter              = N_ITER,
    scoring             = SCORING,
    cv                  = cv,
    random_state        = 42,
    n_jobs              = -1,
    verbose             = 1,
    refit               = True,
)
xgb_search.fit(X_train_res, y_train_res)
print("\nBest XGB params :", xgb_search.best_params_)
print("Best XGB CV F1  :", round(xgb_search.best_score_, 4))
xgb_model = xgb_search.best_estimator_

# ----------------------------------------------------------------
# 8c. LightGBM
# ----------------------------------------------------------------
lgb_param_dist = {
    "clf__n_estimators":  [100, 200, 300],
    "clf__max_depth":     [4, 6, 8, -1],
    "clf__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "clf__num_leaves":    [31, 63, 127],
    "clf__subsample":     [0.6, 0.8, 1.0],
    "clf__reg_alpha":     [0, 0.1, 0.5],
}

lgb_search = RandomizedSearchCV(
    estimator           = make_pipeline(
                            LGBMClassifier(
                                random_state=42, n_jobs=-1, verbose=-1,
                            )
                          ),
    param_distributions = lgb_param_dist,
    n_iter              = N_ITER,
    scoring             = SCORING,
    cv                  = cv,
    random_state        = 42,
    n_jobs              = -1,
    verbose             = 1,
    refit               = True,
)
lgb_search.fit(X_train_res, y_train_res)
print("\nBest LGB params :", lgb_search.best_params_)
print("Best LGB CV F1  :", round(lgb_search.best_score_, 4))
lgb_model = lgb_search.best_estimator_

# ============================================================
# 9. EVALUATE INDIVIDUAL MODELS
# ============================================================
def evaluate_model(name, model, X, y):
    """Print accuracy, ROC-AUC, and full classification report."""
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]
    acc    = accuracy_score(y, y_pred)
    auc_sc = roc_auc_score(y, y_prob)
    print(f"\n{'='*54}")
    print(f"  {name}")
    print(f"  Accuracy : {acc:.4f}  |  ROC-AUC : {auc_sc:.4f}")
    print(f"{'='*54}")
    print(classification_report(y, y_pred, target_names=["Normal", "Botnet"]))
    return acc, auc_sc, y_pred, y_prob


rf_acc,  rf_auc,  y_pred_rf,  y_prob_rf  = evaluate_model("Random Forest", rf_model,  X_test, y_test)
xgb_acc, xgb_auc, y_pred_xgb, y_prob_xgb = evaluate_model("XGBoost",       xgb_model, X_test, y_test)
lgb_acc, lgb_auc, y_pred_lgb, y_prob_lgb = evaluate_model("LightGBM",      lgb_model, X_test, y_test)

# ============================================================
# 10. SOFT-VOTING ENSEMBLE
# ============================================================
from sklearn.ensemble import VotingClassifier

# Each estimator IS a full Pipeline (scaler+PCA+model), so VotingClassifier
# receives raw features and handles everything internally.
ensemble_model = VotingClassifier(
    estimators=[
        ('rf',  rf_model),
        ('xgb', xgb_model),
        ('lgb', lgb_model),
    ],
    voting='soft',
)
ensemble_model.fit(X_train_res, y_train_res)

ens_acc, ens_auc, y_pred_ens, y_prob_ens = evaluate_model(
    "Ensemble (Soft Voting)", ensemble_model, X_test, y_test
)

# ============================================================
# 11. RESULTS TABLE
# ============================================================
results = pd.DataFrame({
    "Model":    ["Random Forest", "XGBoost", "LightGBM", "Ensemble"],
    "Accuracy": [rf_acc,  xgb_acc,  lgb_acc,  ens_acc],
    "ROC-AUC":  [rf_auc,  xgb_auc,  lgb_auc,  ens_auc],
})
print("\n", results.to_string(index=False))

# ============================================================
# 12. VISUALISATIONS
# ============================================================

# ── 12a. Feature Importance — projected back from PCA space ──
# PCA.components_ shape: (n_components, n_original_features)
# RF.feature_importances_ shape: (n_components,)
# Projection: |components|ᵀ @ importances → (n_original_features,)
pca_step = rf_model.named_steps['pca']
clf_step = rf_model.named_steps['clf']

fi_projected = pd.Series(
    np.abs(pca_step.components_).T @ clf_step.feature_importances_,
    index=FEATURE_COLUMNS,
)
fi_projected.nlargest(15).sort_values().plot(kind='barh', figsize=(9, 6), color='steelblue')
plt.title("Top 15 Features — Botnet Detection (RF importance via PCA back-projection)")
plt.xlabel("Projected Importance Score")
plt.tight_layout()
plt.show()

# ── 12b. Confusion Matrix ──
cm = confusion_matrix(y_test, y_pred_ens)
plt.figure(figsize=(6, 4))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Normal', 'Botnet'],
    yticklabels=['Normal', 'Botnet'],
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Ensemble — Confusion Matrix")
plt.tight_layout()
plt.show()

# ── 12c. ROC Curves ──
plt.figure(figsize=(8, 5))
for label, y_prob in [
    ("Random Forest", y_prob_rf),
    ("XGBoost",       y_prob_xgb),
    ("LightGBM",      y_prob_lgb),
    ("Ensemble",      y_prob_ens),
]:
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f"{label}  (AUC={auc(fpr, tpr):.3f})")

plt.plot([0, 1], [0, 1], 'k--', linewidth=0.8)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves — Botnet Detection")
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

# ============================================================
# 13. INFERENCE PIPELINE  (ensemble — supervised)
# ============================================================
ENGINEERED_FEATURES = [
    "packet_ratio", "byte_ratio", "traffic_intensity",
    "avg_packet_size", "ttl_difference", "packet_rate",
]


def prepare_input(input_dict: dict) -> pd.DataFrame:
    """
    Convert a raw network-flow dict into a model-ready DataFrame.
    Steps: OHE → add engineered features → align to training columns.
    """
    df = pd.DataFrame([input_dict])
    df = pd.get_dummies(df)        # OHE categorical fields
    df = add_features(df)          # engineered features (safe_log applied)
    df = df.reindex(columns=FEATURE_COLUMNS, fill_value=0)
    return df


def predict_botnet(input_dict: dict) -> dict:
    """
    Predict botnet vs. normal traffic with a 3-class output and confidence.
    Returns: {'prediction': 'BOTNET'|'SUSPICIOUS'|'NORMAL', 'confidence': float}
    """
    X    = prepare_input(input_dict)
    prob = float(ensemble_model.predict_proba(X)[0][1])

    if prob > 0.60:
        prediction = "BOTNET"
    elif prob < 0.45:
        prediction = "NORMAL"
    else:
        prediction = "SUSPICIOUS"

    return {"prediction": prediction, "confidence": round(prob, 4)}


# ============================================================
# 14. AUTOENCODER ANOMALY DETECTION  (unsupervised)
# ============================================================
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler

# Use original features only (no engineered features) for the AE
X_train_ae_raw = train_df.drop("label", axis=1).drop(columns=ENGINEERED_FEATURES, errors='ignore')
X_test_ae_raw  = test_df.drop("label",  axis=1).drop(columns=ENGINEERED_FEATURES, errors='ignore')

y_train_ae = train_df["label"]
y_test_ae  = test_df["label"]

AE_FEATURE_COLUMNS = X_train_ae_raw.columns.tolist()

# StandardScaler + PCA (fixed 50 components) for the AE pipeline
scaler_ae = StandardScaler()
X_train_ae_sc = scaler_ae.fit_transform(X_train_ae_raw)
X_test_ae_sc  = scaler_ae.transform(X_test_ae_raw)

pca_ae = PCA(n_components=50, random_state=42)
X_train_ae_pca = pca_ae.fit_transform(X_train_ae_sc)
X_test_ae_pca  = pca_ae.transform(X_test_ae_sc)

# Train the AE on CLEAN NORMAL traffic only
X_train_normal = X_train_ae_pca[y_train_ae.values == 0]

q1   = np.percentile(X_train_normal, 5,  axis=0)
q3   = np.percentile(X_train_normal, 95, axis=0)
mask = np.all((X_train_normal >= q1) & (X_train_normal <= q3), axis=1)
X_train_clean  = X_train_normal[mask]

print(f"AE training samples (clean normal traffic): {X_train_clean.shape}")

# Build autoencoder
input_dim    = X_train_clean.shape[1]
inp          = Input(shape=(input_dim,))

x            = Dense(128, activation="relu")(inp)
x            = BatchNormalization()(x)
x            = Dropout(0.2)(x)
x            = Dense(64, activation="relu")(x)
x            = BatchNormalization()(x)
bottleneck   = Dense(32, activation="relu")(x)     # compressed bottleneck

x            = Dense(64,  activation="relu")(bottleneck)
x            = Dense(128, activation="relu")(x)
out          = Dense(input_dim, activation="linear")(x)

autoencoder  = Model(inp, out)
autoencoder.compile(optimizer="adam", loss="mae")
autoencoder.summary()

early_stop = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

history = autoencoder.fit(
    X_train_clean, X_train_clean,
    epochs          = 50,
    batch_size      = 256,
    validation_split= 0.1,
    shuffle         = True,
    callbacks       = [early_stop],
    verbose         = 1,
)

# Reconstruction errors (log-normalised MAE)
def recon_error(X):
    recon = autoencoder.predict(X, verbose=0)
    return np.log1p(np.maximum(np.mean(np.abs(X - recon), axis=1), 0))


mse_train = recon_error(X_train_clean)
mse_test  = recon_error(X_test_ae_pca)

threshold = np.percentile(mse_train, 97)
print("Autoencoder anomaly threshold:", threshold)

ae_predictions = (mse_test > threshold).astype(int)

print("\nAutoencoder Classification Report:")
print(classification_report(y_test_ae, ae_predictions, target_names=["Normal", "Botnet"]))
print(confusion_matrix(y_test_ae, ae_predictions))


def predict_autoencoder(input_dict: dict) -> dict:
    """
    Predict via autoencoder anomaly score.
    Returns: {'prediction': 'BOTNET'|'NORMAL', 'anomaly_score': float}
    """
    df    = pd.DataFrame([input_dict])
    df    = pd.get_dummies(df)
    df    = df.reindex(columns=AE_FEATURE_COLUMNS, fill_value=0)
    X     = scaler_ae.transform(df)
    X     = pca_ae.transform(X)
    error = float(recon_error(X)[0])

    return {
        "prediction":    "BOTNET" if error > threshold else "NORMAL",
        "anomaly_score": round(error, 6),
    }


# ============================================================
# 15. SAMPLE PREDICTIONS
# ============================================================
botnet_sample = {
    "dur": 0.005, "proto": "udp", "service": "-", "state": "INT",
    "spkts": 2000, "dpkts": 2, "sbytes": 120000, "dbytes": 100,
    "rate": 80000, "sttl": 255, "dttl": 5,
}
normal_sample = {
    "dur": 10, "proto": "tcp", "service": "http", "state": "CON",
    "spkts": 40, "dpkts": 45, "sbytes": 1500, "dbytes": 1800,
    "rate": 10, "sttl": 64, "dttl": 64,
}
medium_sample = {
    "dur": 2, "proto": "udp", "service": "dns", "state": "CON",
    "spkts": 300, "dpkts": 50, "sbytes": 40000, "dbytes": 5000,
    "rate": 1500, "sttl": 120, "dttl": 40,
    "sload": 20000, "dload": 3000, "ct_dst_src_ltm": 25,
    "ct_state_ttl": 20, "ct_srv_dst": 18,
    "ct_dst_sport_ltm": 15, "ct_src_dport_ltm": 12, "ct_dst_ltm": 14,
}

print("\n--- Ensemble Predictions ---")
print("Botnet sample :", predict_botnet(botnet_sample))
print("Normal sample :", predict_botnet(normal_sample))
print("Medium sample :", predict_botnet(medium_sample))

print("\n--- Autoencoder Predictions ---")
print("Botnet sample :", predict_autoencoder(botnet_sample))
print("Normal sample :", predict_autoencoder(normal_sample))
print("Medium sample :", predict_autoencoder(medium_sample))

# ============================================================
# 16. SHAP EXPLAINABILITY
# ── Add this as a new cell AFTER Section 15 (Sample Predictions)
#
# WHY here:
#   - Needs trained models (done in Section 8)
#   - Needs X_test / FEATURE_COLUMNS (done in Section 5)
#   - SHAP is post-training analysis, not part of training
#   - We use LightGBM (best ROC-AUC: 0.9053) as the primary explainer
#
# KEY CHALLENGE — Pipeline has PCA inside:
#   TreeExplainer gives SHAP values in PCA space (PC1, PC2, ...)
#   We back-project them to original features via:
#       shap_original = shap_pca @ pca.components_
#   This works because PCA is a LINEAR transformation.
# ============================================================

!pip install shap -q

import shap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ── Helper: extract scaled+PCA-transformed data from a pipeline ──
def transform_pipeline(pipeline, X: pd.DataFrame) -> np.ndarray:
    """Push X through scaler and PCA steps only (not the classifier)."""
    X_scaled = pipeline.named_steps['scaler'].transform(X)
    X_pca    = pipeline.named_steps['pca'].transform(X_scaled)
    return X_pca


def backproject_shap(shap_pca: np.ndarray, pca_step) -> np.ndarray:
    """
    Map SHAP values from PCA space → original feature space.
    shap_pca:   (n_samples, n_components)
    pca_step:   fitted PCA object  [components_ shape: (n_components, n_features)]
    returns:    (n_samples, n_features)
    """
    return shap_pca @ pca_step.components_


# ── Subset test data for SHAP (full 175k rows is too slow) ──
N_SHAP     = 500
X_shap_raw = X_test.sample(n=N_SHAP, random_state=42)
y_shap     = y_test.loc[X_shap_raw.index]

# ── Extract LightGBM classifier and its PCA step ──
lgb_clf  = lgb_model.named_steps['clf']
pca_lgb  = lgb_model.named_steps['pca']
X_shap_pca = transform_pipeline(lgb_model, X_shap_raw)   # (500, n_pca_components)

# ── Build TreeExplainer (fast — uses tree structure directly) ──
explainer = shap.TreeExplainer(lgb_clf)
shap_raw  = explainer.shap_values(X_shap_pca)

# Handle both old (list) and new (array) SHAP API
if isinstance(shap_raw, list):
    # Older SHAP: returns [class0_array, class1_array]
    shap_pca_vals = shap_raw[1]                # botnet class, shape (500, n_components)
    base_val      = explainer.expected_value[1]
else:
    # Newer SHAP: returns single array for positive class
    shap_pca_vals = shap_raw
    base_val      = (explainer.expected_value
                     if np.isscalar(explainer.expected_value)
                     else explainer.expected_value[1])

# Back-project to original feature space
shap_original = backproject_shap(shap_pca_vals, pca_lgb)  # (500, n_original_features)

# DataFrame version for plotting
X_shap_df = pd.DataFrame(X_shap_raw.values, columns=FEATURE_COLUMNS)

# ============================================================
# 16a. GLOBAL — Summary Plot (beeswarm)
#      • Each dot = one sample
#      • X-axis = SHAP value (positive → pushes toward BOTNET)
#      • Color  = feature value (red = high, blue = low)
# ============================================================
print("\n=== Global SHAP Summary — LightGBM (Botnet class) ===")
shap.summary_plot(
    shap_original,
    X_shap_df,
    max_display=20,
    show=True,
)

# ============================================================
# 16b. GLOBAL — Bar Plot (mean |SHAP| per feature)
#      Equivalent to feature importance but SHAP-consistent
# ============================================================
shap.summary_plot(
    shap_original,
    X_shap_df,
    plot_type="bar",
    max_display=20,
    show=True,
)

# ============================================================
# 16c. DEPENDENCE PLOT — top feature
#      Shows how the top-1 feature interacts with the top-2 feature
# ============================================================
mean_abs_shap = np.abs(shap_original).mean(axis=0)
top2_feats    = pd.Series(mean_abs_shap, index=FEATURE_COLUMNS).nlargest(2).index.tolist()

print(f"\n=== SHAP Dependence — '{top2_feats[0]}' colored by '{top2_feats[1]}' ===")
shap.dependence_plot(
    top2_feats[0],
    shap_original,
    X_shap_df,
    interaction_index=top2_feats[1],
    show=True,
)

# ============================================================
# 16d. LOCAL — Waterfall for 1 Botnet + 1 Normal sample
#      Shows WHICH features pushed THIS specific prediction
# ============================================================
botnet_local_idx = (y_shap == 1).values.argmax()   # first botnet sample position
normal_local_idx = (y_shap == 0).values.argmax()   # first normal sample position

for label, idx in [("BOTNET sample", botnet_local_idx),
                   ("NORMAL sample", normal_local_idx)]:
    exp = shap.Explanation(
        values        = shap_original[idx],
        base_values   = base_val,
        data          = X_shap_df.iloc[idx].values,
        feature_names = FEATURE_COLUMNS,
    )
    print(f"\n=== SHAP Waterfall — {label} ===")
    shap.waterfall_plot(exp, max_display=15, show=True)

# ============================================================
# 16e. FORCE PLOT — interactive (Colab inline)
# ============================================================
shap.initjs()
print("\n=== Force Plot — Botnet Sample (run in Colab for interactive view) ===")
fp = shap.force_plot(
    base_val,
    shap_original[botnet_local_idx],
    X_shap_df.iloc[botnet_local_idx],
    feature_names=FEATURE_COLUMNS,
)
display(fp)   # only works in Jupyter/Colab

# ============================================================
# 16f. INFERENCE SHAP — explain any new prediction
#      Call this after predict_botnet() to understand WHY
# ============================================================
def explain_prediction(input_dict: dict, top_n: int = 10) -> pd.Series:
    """
    Print the top contributing features for a single prediction.

    Usage:
        result = predict_botnet(my_sample)
        explain_prediction(my_sample)
    """
    X_input   = prepare_input(input_dict)            # → DataFrame, aligned to FEATURE_COLUMNS
    X_pca_inp = transform_pipeline(lgb_model, X_input)  # → ndarray (1, n_components)

    sv_raw = explainer.shap_values(X_pca_inp)
    if isinstance(sv_raw, list):
        sv_pca = sv_raw[1]        # (1, n_components)
    else:
        sv_pca = sv_raw

    sv_orig  = backproject_shap(sv_pca, pca_lgb)     # (1, n_features)
    contrib  = pd.Series(sv_orig[0], index=FEATURE_COLUMNS)

    prob = float(lgb_model.predict_proba(X_input)[0][1])
    pred = "BOTNET" if prob > 0.6 else ("NORMAL" if prob < 0.45 else "SUSPICIOUS")

    print(f"\n{'─'*58}")
    print(f"  Prediction : {pred}   (confidence: {prob:.4f})")
    print(f"  Base value : {base_val:.4f}  → final log-odds: {base_val + contrib.sum():.4f}")
    print(f"{'─'*58}")
    print(f"  {'Feature':<30} {'SHAP':>9}   Direction")
    print(f"  {'─'*54}")
    for feat in contrib.abs().nlargest(top_n).index:
        val   = contrib[feat]
        arrow = "▲ → BOTNET" if val > 0 else "▼ → NORMAL"
        print(f"  {feat:<30} {val:>+9.4f}   {arrow}")
    print()

    # Mini waterfall
    exp = shap.Explanation(
        values        = sv_orig[0],
        base_values   = base_val,
        data          = X_input.iloc[0].values,
        feature_names = FEATURE_COLUMNS,
    )
    shap.waterfall_plot(exp, max_display=10, show=True)
    return contrib


# ── Test it on all three sample types ──
print("\n\n" + "="*60)
print("  SHAP EXPLANATIONS FOR SAMPLE PREDICTIONS")
print("="*60)

explain_prediction(botnet_sample)
explain_prediction(normal_sample)
explain_prediction(medium_sample)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler

my_sample = {
    "dur":     5.2,
    "proto":   "tcp",       # raw string — OHE is handled internally
    "service": "http",
    "state":   "CON",
    "spkts":   80,
    "dpkts":   90,
    "sbytes":  3200,
    "dbytes":  3600,
    "rate":    25.0,
    "sttl":    64,
    "dttl":    64,
    # optional extra fields if available:
    "sload":   100, "dload": 110,
    "ct_dst_src_ltm": 3, "ct_state_ttl": 2,
}

print(predict_botnet(my_sample))
# → {'prediction': 'NORMAL', 'confidence': 0.1234}

print(predict_autoencoder(my_sample))
# → {'prediction': 'NORMAL', 'anomaly_score': 0.002341}

botnet_sample_4 = {
    "dur": 0.01,
    "proto": "udp",
    "service": "-",
    "state": "INT",
    "spkts": 3000,
    "dpkts": 5,
    "sbytes": 200000,
    "dbytes": 200,
    "rate": 90000,
    "sttl": 255,
    "dttl": 5,
}
print(predict_autoencoder(botnet_sample_4))

import joblib
import pickle

# ── Save sklearn ensemble (RF + XGB + LGB pipelines) ──
joblib.dump(ensemble_model, "botnet_ensemble.pkl")
joblib.dump({
    "feature_columns":    FEATURE_COLUMNS,
    "ae_feature_columns": AE_FEATURE_COLUMNS,
    "engineered_features":ENGINEERED_FEATURES,
    "scaler_ae":          scaler_ae,
    "pca_ae":             pca_ae,
    "ae_threshold":       threshold,
}, "botnet_metadata.pkl")

# ── Save Keras autoencoder ──
autoencoder.save("botnet_autoencoder.keras")

print("All models saved.")

"""### Using the saved models in other programs"""

def recon_error(X):
    recon = autoencoder.predict(X, verbose=0)
    return np.log1p(np.maximum(np.mean(np.abs(X - recon), axis=1), 0))

def prepare_input(input_dict: dict) -> pd.DataFrame:
    """
    Convert a raw network-flow dict into a model-ready DataFrame.
    Steps: OHE → add engineered features → align to training columns.
    """
    df = pd.DataFrame([input_dict])
    df = pd.get_dummies(df)        # OHE categorical fields
    df = add_features(df)          # engineered features (safe_log applied)
    df = df.reindex(columns=FEATURE_COLUMNS, fill_value=0)
    return df

def predict_autoencoder(input_dict: dict) -> dict:
    """
    Predict via autoencoder anomaly score.
    Returns: {'prediction': 'BOTNET'|'NORMAL', 'anomaly_score': float}
    """
    df    = pd.DataFrame([input_dict])
    df    = pd.get_dummies(df)
    df    = df.reindex(columns=AE_FEATURE_COLUMNS, fill_value=0)
    X     = scaler_ae.transform(df)
    X     = pca_ae.transform(X)
    error = float(recon_error(X)[0])

    return {
        "prediction":    "BOTNET" if error > threshold else "NORMAL",
        "anomaly_score": round(error, 6),
    }

def predict_botnet(input_dict: dict) -> dict:
    """
    Predict botnet vs. normal traffic with a 3-class output and confidence.
    Returns: {'prediction': 'BOTNET'|'SUSPICIOUS'|'NORMAL', 'confidence': float}
    """
    X    = prepare_input(input_dict)
    prob = float(ensemble_model.predict_proba(X)[0][1])

    if prob > 0.60:
        prediction = "BOTNET"
    elif prob < 0.45:
        prediction = "NORMAL"
    else:
        prediction = "SUSPICIOUS"

    return {"prediction": prediction, "confidence": round(prob, 4)}

from google.colab import drive
#drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/botnet_model')

import joblib
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model

# ── Load everything ──
ensemble_model = joblib.load("drive/MyDrive/botnet_model/botnet_ensemble.pkl")
meta           = joblib.load("drive/MyDrive/botnet_model/botnet_metadata.pkl")
autoencoder    = load_model("drive/MyDrive/botnet_model/botnet_autoencoder.keras")

FEATURE_COLUMNS     = meta["feature_columns"]
AE_FEATURE_COLUMNS  = meta["ae_feature_columns"]
ENGINEERED_FEATURES = meta["engineered_features"]
scaler_ae           = meta["scaler_ae"]
pca_ae              = meta["pca_ae"]
threshold           = meta["ae_threshold"]

# ── Re-define helpers (copy from training script) ──
def safe_log(x):
    return np.log1p(np.clip(x, 0, 1e6))

def add_features(df):
    df = df.copy()
    df["packet_ratio"]      = safe_log(df["spkts"] / (df["dpkts"] + 1))
    df["byte_ratio"]        = safe_log(df["sbytes"] / (df["dbytes"] + 1))
    df["traffic_intensity"] = safe_log(df["rate"] * df["dur"])
    df["avg_packet_size"]   = safe_log(
        (df["sbytes"] + df["dbytes"]) / (df["spkts"] + df["dpkts"] + 1))
    df["ttl_difference"]    = safe_log(abs(df["sttl"] - df["dttl"]))
    df["packet_rate"]       = safe_log(
        (df["spkts"] + df["dpkts"]) / (df["dur"] + 0.001))
    return df

my_sample = {
    "dur":     5.2,
    "proto":   "tcp",       # raw string — OHE is handled internally
    "service": "http",
    "state":   "CON",
    "spkts":   80,
    "dpkts":   90,
    "sbytes":  3200,
    "dbytes":  3600,
    "rate":    25.0,
    "sttl":    64,
    "dttl":    64,
    # optional extra fields if available:
    "sload":   100, "dload": 110,
    "ct_dst_src_ltm": 3, "ct_state_ttl": 2,
}
# ── Now predict normally ──
print(predict_botnet(my_sample))
print(predict_autoencoder(my_sample))